project:
  type: website
  output-dir: docs

website:
  title: "{{< var course.number >}}"
  google-analytics: ""
  repo-url: https://github.com/hgoers/GVPT339F
  repo-actions: [issue]

  favicon: "/files/img/hex-testudo.png"

  navbar:
    pinned: true
    background: "#C31832"
    right:
      - href: index.qmd
        text: Home
      - href: content/00-introduction.qmd
        text: Content

  sidebar:
    - title: "Content"
      style: "docked"
      contents:
        - section: "Session 0"
          contents: 
            - content/00-introduction.qmd
        - section: "Session 1"
          contents:         
            - content/01-visualization.qmd         
            - content/01-measurement.qmd
        - section: "Session 2"
          contents: 
            - content/02-transformation.qmd
            - content/02-experiments.qmd
        - section: "Session 3"
          contents: 
            - content/03-wrangling.qmd
            - content/03-surveys_to_pops.qmd
        - section: "Session 4"
          contents: 
            - content/04-merging.qmd
            - content/04-bivariate.qmd
        - section: "Session 5"
          contents: 
            - content/05-programming.qmd
            - content/05-linear_regression.qmd
        - section: "Session 6"
          contents: 
            - content/06-communicating.qmd
            - content/06-probability.qmd
        - section: "Session 7"
          contents: 
            - content/07-uncertainty.qmd
            
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-Non Commercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [Heavily inspired by course websites built by Dr Andrew Heiss](https://www.andrewheiss.com/teaching/)

format:
  html:
    theme: litera
    css: html/custom.css
    toc: true
    highlight-style: monokai

editor: visual

